Add LICENSE file to allow installing with yazi-plugin-manager
This commit adds a LICENSE file to the repository to allow installing
the plugin with yazi-plugin-manager.

The LICENSE file is a copy of the MIT license, with the copyright
holder's name having been changed to the repository owner's username.

This fixes the following error:

```text
  Deploying package `eza-preview.yazi`

Error: Failed to copy `/home/user/.local/state/yazi/packages/0441ad06d7d13efa65838c08e0fd41ba/LICENSE` to `/home/user/.config/yazi/plugins/eza-preview.yazi/LICENSE`

Caused by:
    No such file or directory (os error 2)
```

<https://yazi-rs.github.io/docs/plugins/overview>